### ISSUE TITLE
can you make an uninstall.sh script too ?

### ISSUE THREAD

**Issue by rsoorajs** [roshanconnor123/mediaserver#1]
how can we remove all installed stuffs if we dont want ?

**Comment by roshanconnor123** [comment]
Sure
I will add that too

**Comment by rsoorajs** [comment]
> Sure
> I will add that too

Thank you.i am trying the script.but cant uninstall jellyfin player stuffs,which installed,so the uninstall script will be very helpful

**Comment by bletnieehjom** [comment]
> Sure
> I will add that too

Any update on this?
